### ISSUE TITLE
 매출액과 투자금, 시장 점유율 분석으로 자소서 키워드 뽑기

### ISSUE THREAD

**Issue by tjsgh531** [twoside-EDA/company_analyze#13]
## Description

삼성전자와 경쟁사의 매출액 투자금 시장점유율을 비교해서 자소서에 쓸만한 키워드를 뽑아봅시다.

## Tasks

- [x] 삼성전자 매출액(전체, 부문별, 제품별) 데이터 전처리 밑 시각화
- [x] 년도 별 총 매출액 csv 만들기
- [x] 년도 별 부문 별 매출액 csv 만들기
- [x] 년도 별 총 매출액 + 부문 별 매출액 histplot (multiple =True)시각화 하기

=> 메모리 제품에서 큰 매출액 감소를 확인 가능
=> 메모리 제품 매출액 감소 요인에 대한 EDA 하자!!

#### 매출액 부문

- [ ] SK하이닉스 매출 데이터 가져와요.
- [ ] 삼성전자와 매출 데이터 비교 시각화 해요.

#### 가격 변동률

- [ ] SK하이닉스 가격 변동률 데이터 가져와요.
- [ ] 삼성전자와 가격 변동률을 비교해요.

## References

- [ 삼성전자 사업 보고서 ](https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240312000736)
- [ 삼성전자 메모리 매출액 관련 기사1 ](https://dealsite.co.kr/articles/114457) 
- [반도체 산업 EDA 보고서](https://www.eugenefn.com/common/files/amail//20230523_B45_swlee6591_803.pdf)
- 매출액은 줄었는데 영업 이익은 늘었다.. 왜 그런지 분석 필요
