### ISSUE TITLE
크롤링을 이용해서 삼성전자 사업보고서 데이터화

### ISSUE THREAD

**Issue by tjsgh531** [twoside-EDA/company_analyze#2]
## Description

삼성전자 사업보고서에 있는 모든 테이블들을 df로 바꿔버리겠습니다.
selenium 과  beautiful soup을 이용합니다.

## Tasks

- [x] 삼성전자 2023.12 사업보고서 페이지로 들어가기
- [x] 페이지 내에 모든 table 태그를 크롤링 하여 dataframe list반환 함수 만들기
- [x] table태그 크롤링 하여 df list 반환 하는 함수 예외처리
- [x] dummy data 뽑기
- [x] 전체 테이블 개수 확인하기 => 1605개
- [x] 원하는 세부 페이지 목록 만들기
- [x] 세부 페이지 이동하면서 table 태그 크롤링 함수 실행

## References

- [삼성전자 사업 보고서 2023.12](https://dart.fss.or.kr/dsaf001/main.do?rcpNo=20240312000736)
