### ISSUE TITLE
관련 EDA 프로젝트 조사

### ISSUE THREAD

**Issue by journeythrunrun** [twoside-EDA/company_analyze#3]
## Description
회사 재무 데이터를 이용해 잘한 EDA 작업물, 프로젝트를 찾아보겠습니다.
(잘 된, 잘 한 것에서 배울 수 있는 부분 배우기)

## Tasks
> 소요 시간, 프로젝트 기간도 조금 고려하여 각각에 관해 어느정도의 자료만 살펴 보았음. 진행 중 필요하면 해당 항목 추가 진행하기도 할 것임.

- [x] 캐글의 Dataset, Code 등
- [x] 주식 
   > 세부 EDA 항목도 우리 프로젝트와의 fit이 높은 부분이 별로 없음

- [x] 논문 
   > 오픈소스보다 기술적 이론적인 측면이 많음

- [x] 전문가가 보기에 잘 된 EDA 프로젝트나 한 것 찾기 및 살펴보기 (분석 논리 흐름, 잘한 프로젝트가 무엇인지 출발지~도착지 습득) 
  > - => (프로젝트 의의 및 목표 관점에서, 전체 진행 구간에 있어서 약간 덜 명확한 흐릿한 부분이 있지만) 어느정도 전문적인 기업분석 자료를 보고 필요하다고 여겨지는 의의로 우선 진행. 

  > 예전에 봤던거[대기업 관련 전문가 시점 잘한 프로젝트 (실제 전문가가 한 것보다는 약할 수 있음) ] 따로 저장이나 필기를 안해둔 것 같음. 
  > 어느정도 검색해봤는데 전문성 높은 자료 & 인사이트 및 결론까지 있는 좋은 오픈소스를 바로 찾지는 못함

  + [삼성SDS brightics AI](https://www.brightics.ai/community/knowledge-sharing/detail/7059)

- [x] Techinsights
- [x] [나중] 잘 한 분석 자료 (그래프 포함)  

## References
- [ 캐글 데이터셋 | 자료의 중요성, 프로젝트와의 fit : 높진 않음 ](https://www.kaggle.com/datasets/atharvaarya25/financials)
  + [ 관련 주피터노트북 ](https://www.kaggle.com/code/rajatraj0502/company-financials-dataset)
- [ 데이터 항목 ](https://www.kaggle.com/datasets/sameerprogrammer/detailed-financial-data-of-4456-nse-and-bse-company)

- [ EDA 진행 흐름 [포항공대 컴퓨터공학 석사] ](https://letsmakemyselfprogrammer.tistory.com/22)
- [ EDA 진행 흐름 | EDA 진행 단계 마다 선택 할 수 있는 항목 | 회계학 분야 연구를 주로 한다는 사람이 한 기업 재무정보 활용 EDA 진행 | 회계학 분야 연구를 주로 하는 사람이 말한 손은정 교수님이 알려주신 EDA 프롬프트 [인터넷 자료] ](https://chat.openai.com/share/e04add60-cd0b-43ab-b136-3110309366c2)
  + [사용 시 참고할 사항 | 출처](https://www.gpters.org/c/data-science/eda)
