### ISSUE TITLE
삼성전자 사업보고서 데이터 전처리 및 시각화

### ISSUE THREAD

**Issue by tjsgh531** [twoside-EDA/company_analyze#7]
## Description

크롤링을 통해 가져온 데이터를 전처리하고 시각화 해보겠습니다.

## Tasks

- [x] 회사 개요 데이터(7) 전처리 및 시각화
- [x] 주요 제품 및 서비스 데이터(4) 전처리 및 시각화
- [x] 회사의 연혁 데이터 (4) 전처리 및 시각화
- [ ] 원재료 및 생산설비 데이터(14) 전처리 및 시각화
- [ ] 매출 및 수주상황(9) 전처리 및 시각화
- [ ] 주요계약 및 연구개발활동 데이터(4) 전처리 및 시각화
- [ ] 기타 참고사항 데이터(9) 전처리 및 시각화
- [ ] 이사의 경영진단 및 분석의견 데이터(13) 전처리 및 시각화

## References

- [ EDA 진행 흐름 [포항공대 컴퓨터공학 석사] ](https://letsmakemyselfprogrammer.tistory.com/22)

- [ EDA 진행 흐름 | EDA 진행 단계 마다 선택 할 수 있는 항목 | 회계학 분야 연구를 주로 한다는 사람이 한 기업 재무정보 활용 EDA 진행 | 회계학 분야 연구를 주로 하는 사람이 말한 손은정 교수님이 알려주신 EDA 프롬프트 [인터넷 자료] ](https://chat.openai.com/share/e04add60-cd0b-43ab-b136-3110309366c2)

**Comment by tjsgh531** [comment]
목적에 맞게 그때그때 필요한 데이터를 찾기로해요...
